In [1]:
import numpy as np

a = np.array([1, 2, 3])
a + a

array([2, 4, 6])

In [2]:
def print_array_derails(a):
    print(f'Dimensions: {a.ndim}, shape: {a.shape}, dtype: {a.dtype}')

In [3]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
print_array_derails(a)

Dimensions: 1, shape: (8,), dtype: int64


In [5]:
a = a.reshape([2, 4])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print_array_derails(a)

Dimensions: 2, shape: (2, 4), dtype: int64


In [7]:
a = a.reshape([2, 2, 2])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
print_array_derails(a)

Dimensions: 3, shape: (2, 2, 2), dtype: int64


In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
x.shape

(2, 3)

In [10]:
x.shape = (6,)
x

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [11]:
x = x.astype("int64")
x

array([1, 2, 3, 4, 5, 6])

In [12]:
x.dtype

dtype('int64')

In [13]:
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a.dtype

dtype('float64')

In [15]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
empty_array = np.empty((2, 3))
empty_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.random.random((2,3))

array([[0.10090238, 0.23819282, 0.5210982 ],
       [0.97096809, 0.33128857, 0.86836122]])

In [18]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [19]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
a[2]

3

In [21]:
a[3:5]

array([4, 5])

In [22]:
a[:4:2]

array([1, 3])

In [23]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [24]:
a = np.arange(8)
a.shape = (2, 2, 2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
a1 = a[1]
a1

array([[4, 5],
       [6, 7]])

In [26]:
np.array_equal(a1,a[1,:])

True

In [27]:
np.array_equal(a1,a[1,:,:])

True

In [28]:
np.array_equal(a[...,0], a[:,:,0])

True

In [29]:
a = np.array([45, 65, 76, 32, 99, 22])
a < 50

array([ True, False, False,  True, False,  True])

In [30]:
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
a.min(axis=1)

array([0, 4])

In [32]:
a.sum(axis=0)

array([ 4,  6,  8, 10])

In [33]:
# Average along second axis
a.mean(axis=1)

array([1.5, 5.5])

In [34]:
# standard deviation
a.std(axis=1)

array([1.11803399, 1.11803399])

In [35]:
pi = np.pi
a = np.array([pi, pi / 2, pi / 4, pi / 6])
np.degrees(a)

array([180.,  90.,  45.,  30.])

In [36]:
sin_a = np.sin(a)
sin_a

array([1.22464680e-16, 1.00000000e+00, 7.07106781e-01, 5.00000000e-01])

In [37]:
np.round(sin_a, 7)

array([0.       , 1.       , 0.7071068, 0.5      ])

In [38]:
a = np.arange(8).reshape((2, 4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
np.cumsum(a, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22]])

In [40]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [41]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1 :] / n

In [42]:
a = np.arange(6)
csum = np.cumsum(a)
csum

array([ 0,  1,  3,  6, 10, 15])

In [43]:
print(csum[3:])
print(csum[:-3])
csum[3:] = csum[3:] - csum[:-3]
csum

[ 6 10 15]
[0 1 3]


array([ 0,  1,  3,  6,  9, 12])

In [44]:
a = np.arange(10)
moving_average(a, 4)

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])